[package]
name = "leipzig-university-slides"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Niklas Dießner <@TheBlackSheep3>"]
license = "MIT"
description = "Presentation slides for the Leipzig University."
repository = "https://github.com/TheBlackSheep3/leipzig-university-slides"
keywords = ["presentation", "slides", "polylux", "university", "leipzig", "Leipzig University", "Universität Leipzig"]
categories = ["presentation"]
disciplines = []
# compiler = ""
exclude = [
  ".github",
  "docs",
  "scripts",
  "tests",
  ".typstignore",
  "Justfile",
  "thumbnail.svg",
]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
